### ISSUE TITLE
BG2EE Denoised  Areas Works on EET: Here's How!

### ISSUE THREAD

**Issue by Endarire** [WillScarlettOhara/BG2EE_AI_Denoised_Areas#2]
Greetings, @WillScarlettOhara!

Use [this TP2 file](https://drive.google.com/file/d/1K1V7DB2gkjLfKF2Enw_f0VGvo_47dKGT/view?usp=share_link) instead of the one normally distributed and this mod works easily on BG2EE and EET!  (I just changed the line where it says bg2ee to also put beside it eet.

Enjoy!

**Comment by Endarire** [comment]
@WillScarlettOhara 
I forked your code and updated it to EET compatibility [here](https://github.com/Endarire/BG2EE_AI_Denoised_Areas).  Enjoy!

**Comment by WillScarlettOhara** [comment]
Thank you 😉
